### ISSUE TITLE
css-loaderのバージョンアップに伴うlocalIdentNameの記述位置の変更について

### ISSUE THREAD

**Issue by isumidaichi** [polyxx/nekomimi-frontend#1]
書籍より勉強させて頂いた者です 🧑‍💻 

css-loaderのoptionに関して書籍内の実装だと以下のようなエラーでbuildができません。
```
ERROR in ./src/css/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src!./src/css/index.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
- options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
   at validate (/Users/daichi/nekomimi-frontend/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:88:11)
   at Object.loader (/Users/daichi/nekomimi-frontend/node_modules/css-loader/dist/index.js:36:28)
```
原因は`css-loader`バージョンアップによるもので下記のように記述方法を変えれば正常に動作することを確認しました。参考にしたurl貼っておきます。
https://github.com/rails/webpacker/issues/2197
```
options: {
  modules: {
    localIdentName: '[name]__[local]--[hash:base64:5]'
  },
   importLoaders: 1
}
```

僭越ながらとても勉強させて頂いた書籍だったのでこちらでご報告させて頂きました。

**Comment by polyxx** [comment]
（返信が大変遅くなりました 🙇 ）

著者の汐瀬なぎです。この度は拙作をご購入いただき、ありがとうございます 🙏 
ご指摘いただいた通り、css-loaderがv3.0.0よりoptionsの指定方法が変更となったため、書籍の指定方法では動作しないことを確認しました。
書籍の内容自体が少し古くなっているため、このように調べて修正いただくような格好になっており申し訳ないです 🙇 

修正内容につきましては、READMEにてその旨を追記させていただきます。
ご報告いただきありがとうございました！
